import { 
  FiGlobe, 
  FiCpu, 
  FiSearch, 
  FiUsers, 
  FiActivity, 
  FiDollarSign, 
  FiSettings, 
  FiCheckCircle, 
  FiAlertCircle,
  FiChevronDown,
  FiMail,
  FiPhone,
  FiMapPin,
  FiStar,
  FiZap,
  FiLayers,
  FiClock,
  FiCreditCard,
  FiTwitter,
  FiGithub,
  FiLinkedin,
  FiTrash2,
  FiPlus,
  FiArrowRight,
  FiArrowLeft,
  FiLink,
  FiShield,
  FiFolder,
  FiTag,
  FiEdit3,
  FiEye,
  FiEyeOff,
  FiUser,
  FiBook,
  FiCopy,
  FiCheck,
  FiX,
  FiSend
} from 'react-icons/fi'

export const iconMap = {
  design: FiGlobe,
  cloud: FiCpu,
  seo: FiSearch,
  search: FiSearch,
  users: FiUsers,
  user: FiUser,
  activity: FiActivity,
  dollar: FiDollarSign,
  settings: FiSettings,
  check: FiCheckCircle,
  checkmark: FiCheck,
  alert: FiAlertCircle,
  'chevron-down': FiChevronDown,
  mail: FiMail,
  phone: FiPhone,
  location: FiMapPin,
  star: FiStar,
  zap: FiZap,
  project: FiLayers,
  layers: FiLayers,
  clock: FiClock,
  wallet: FiCreditCard,
  twitter: FiTwitter,
  github: FiGithub,
  linkedin: FiLinkedin,
  support: FiPhone,
  security: FiShield,
  code: FiCpu,
  trash: FiTrash2,
  plus: FiPlus,
  'arrow-right': FiArrowRight,
  'arrow-left': FiArrowLeft,
  link: FiLink,
  folder: FiFolder,
  tag: FiTag,
  edit: FiEdit3,
  globe: FiGlobe,
  eye: FiEye,
  eyeSlash: FiEyeOff,
  bookOpen: FiBook,
  copy: FiCopy,
  x: FiX,
  send: FiSend
}
